[package]
name = "path_import_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"

[patch.crates-io]
naga_oil = { path="../naga_oil" }